import os

def scan_directory(path):
    print("Scanning...")
    threats = {
        "WindowsHandler.exe": "Stealer Trojan", # fake process windows scan
        "rndll86.exe": "Other Wirus: Keylogger, Rat, inc.",
        "encryptor.exe": "Ransomeware",
        "decryptor.dll": "Ransomeware",
        "system32.dll": "Spyware inc.",
        "taskmanager.exe": "Spyware inc.",
        "driver.sys": "rootkit",
        "ntoskrnl.exe": "rootkit",
        "systemupdate.exe": "Keylogger",
        "keyboarddriver.sys": "Keylogger",
        "explorer.exe": "Trojan",
        "svchost.exe": "Trojan",
        "cryptolocker.exe": "Ransomeware",
        "locky.exe": "Ransomeware",
        "cryptominer.exe": "Cryptovalutes Miner",
        "miner.exe": "Cryptovalutes Miner",
        "bitcoin.exe": "Cryptovalutes Miner",
        "zeustrojan.exe": "Trojan",
        "Spyeye.exe": "Trojan",
        "backdoor.bladabindi.exe": "Trojan",
        "keylogger.exe": "Keylogger",
        "darkcometrat.exe": "Keylogger.rat",
        "poisonlvy.exe": "Keylogger",
        "alureon.sys": "rootkit",
        "zeroaccess.sys": "rootkit",
        "tdl-4.sys": "rootkit",
        "adware.eorezo.exe": "Spyware",
        "winspy.exe": "Spyware",
        "finfisher.exe": "Spyware",
        "gandcrab.exe": "Ransomeware",
        "ryuk.exe": "Ransomeware",
        "maze.exe": "Ransomeware",
        "darkcomet.exe": "Ransomeware",
        "xxx.exe": "Ransomeware",
        "keybase.exe": "Keylogger",
        "blackshades.exe": "Keylogger",
        "elitekeylogger.exe": "Keylogger",
        "none.exe": "Keylogger inc.",
        "key.exe": "Keylogger",
        "keysend.exe": "Keylogger",
        "keysender.exe": "Keylogger",
        "adware.exe": "Spyware",
        "end.exe": "Trojan",
        "logger.exe": "Keylogger",
        "rootstop.sys": "rootkit",
        "rustock.sys": "rootkit",
        "hackerdefender.sys": "rootkit",
        "vanquish.sys": "rootkit",
        "finspy.exe": "Spyware",
        "coolwebsearch.exe": "Spyware",
        "gator.exe": "Spyware",
        "cerber.cerber": "Ransomeware",
        "samsam.weapologize": "Ransomeware",
        "Dharma.dharma": "Ransomeware",
        "spybot.exe": "Trojan",
        "netbus.exe": "Trojan",
        "subseven.exe": "Trojan",
        "zbot.dll": "Keylogger",
        "elitestealer.exe": "Keylogger",
        "keysweeper.js": "Keylogger",
        "necurs.sys": "rootkit",
        "tdss.sys": "rootkit",
        "ntrootkit.sys": "rootkit",
        "superfish.exe": "Spyware",
        "browsersearch": "Spyware",
        "finfisher.exe": "Spyware",
        "zango.exe": "Spyware",
        "teslacrypt.ecc": "Ransomeware",
        "crysis.xtbl": "Ransomeware",
        "spora.spora": "Ransomeware",
        "emolet.exe": "Trojan",
        "vawtrak.dll": "Trojan",
        "zeusgameover.exe": "Trojan",
        "hawkeye.exe": "Keylogger",
        "havkeye.exe": "Keylogger",
        "havkey.exe": "Keylogger",
        "havekeye.exe": "Keylogger",
        "havekey.exe": "Keylogger",
        "adwind.jar": "Keylogger",
        "predatorpain.exe": "Keylogger",
        "predator.exe": "Keylogger",
        "albinosun.sys": "rootkit",
        "cerberp.sys": "rootkit",
        "hackerguard.sys": "rootkit",
        "hackerguardian.sys": "rootkit",
        "xtremerat.exe": "Keylogger.rat",
        "zeus.exe": "Spyware",
        # No Extension
        "WindowsHandler": "Stealer Trojan",
        "rndll86": "Inne wirusy: Keylogger, Rat, itp.",
        "encryptor": "Ransomware",
        "decryptor": "Ransomware",
        "system32": "Spyware",
        "taskmanager": "Spyware",
        "driver": "Rootkit",
        "ntoskrnl": "Rootkit",
        "systemupdate": "Keylogger",
        "keyboarddriver": "Keylogger",
        "explorer": "Trojan",
        "svchost": "Trojan",
        "cryptolocker": "Ransomware",
        "locky": "Ransomware",
        "cryptominer": "Cryptovalutes Miner",
        "miner": "Cryptovalutes Miner",
        "bitcoin": "Cryptovalutes Miner",
        "zeustrojan": "Trojan",
        "Spyeye": "Trojan",
        "backdoor.bladabindi": "Trojan",
        "keylogger": "Keylogger",
        "darkcometrat": "Keylogger.RAT",
        "poisonlvy": "Keylogger",
        "alureon": "Rootkit",
        "zeroaccess": "Rootkit",
        "tdl-4": "Rootkit",
        "adware.eorezo": "Spyware",
        "winspy": "Spyware",
        "finfisher": "Spyware",
        "gandcrab": "Ransomware",
        "ryuk": "Ransomware",
        "maze": "Ransomware",
        "darkcomet": "Ransomware",
        "xxx": "Ransomware",
        "keybase": "Keylogger",
        "blackshades": "Keylogger",
        "elitekeylogger": "Keylogger",
        "none": "Keylogger, itp.",
        "key": "Keylogger",
        "keysend": "Keylogger",
        "keysender": "Keylogger",
        "adware": "Spyware",
        "end": "Trojan",
        "logger": "Keylogger",
        "rootstop": "Rootkit",
        "rustock": "Rootkit",
        "hackerdefender": "Rootkit",
        "vanquish": "Rootkit",
        "finspy": "Spyware",
        "coolwebsearch": "Spyware",
        "gator": "Spyware",
        "cerber": "Ransomware",
        "samsam": "Ransomware",
        "Dharma": "Ransomware",
        "spybot": "Trojan",
        "netbus": "Trojan",
        "subseven": "Trojan",
        "zbot": "Keylogger",
        "elitestealer": "Keylogger",
        "keysweeper": "Keylogger",
        "necurs": "Rootkit",
        "tdss": "Rootkit",
        "ntrootkit": "Rootkit",
        "superfish": "Spyware",
        "browsersearch": "Spyware",
        "finfisher": "Spyware",
        "zango": "Spyware",
        "teslacrypt": "Ransomware",
        "crysis": "Ransomware",
        "spora": "Ransomware",
        "emotet": "Trojan",
        "vawtrak": "Trojan",
        "zeusgameover": "Trojan",
        "hawkeye": "Keylogger",
        "havkeye": "Keylogger",
        "havkey": "Keylogger",
        "havekeye": "Keylogger",
        "havekey": "Keylogger",
        "adwind": "Keylogger",
        "predatorpain": "Keylogger",
        "predator": "Keylogger",
        "albinosun": "Rootkit",
        "cerberp": "Rootkit",
        "hackerguard": "Rootkit",
        "hackerguardian": "Rootkit",
        "xtremerat": "Keylogger.RAT",
        "zeus": "Spyware",
        # extension exe
    "WindowsHandler.exe": "Stealer Trojan" ,
    "rndll86.exe": "Inne wirusy: Keylogger, Rat, itp.",
    "encryptor.exe": "Ransomware",
    "decryptor.exe": "Ransomware",
    "system32.dll": "Spyware",
    "taskmanager.exe": "Spyware",
    "driver.sys": "Rootkit",
    "ntoskrnl.exe": "Rootkit",
    "systemupdate.exe": "Keylogger",
    "keyboarddriver.sys": "Keylogger",
    "explorer.exe": "Trojan",
    "svchost.exe": "Trojan",
    "cryptolocker.exe": "Ransomware",
    "locky.exe": "Ransomware",
    "cryptominer.exe": "Cryptovalutes Miner",
    "miner.exe": "Cryptovalutes Miner",
    "bitcoin.exe": "Cryptovalutes Miner",
    "zeustrojan.exe": "Trojan",
    "Spyeye.exe": "Trojan",
    "backdoor.bladabindi.exe": "Trojan",
    "keylogger.exe": "Keylogger",
    "darkcometrat.exe": "Keylogger.rat",
    "poisonlvy.exe": "Keylogger",
    "alureon.sys": "Rootkit",
    "zeroaccess.sys": "Rootkit",
    "tdl-4.sys": "Rootkit",
    "adware.eorezo.exe": "Spyware",
    "winspy.exe": "Spyware",
    "finfisher.exe": "Spyware",
    "gandcrab.exe": "Ransomware",
    "ryuk.exe": "Ransomware",
    "maze.exe": "Ransomware",
    "darkcomet.exe": "Ransomware",
    "xxx.exe": "Ransomware",
    "keybase.exe": "Keylogger",
    "blackshades.exe": "Keylogger",
    "elitekeylogger.exe": "Keylogger",
    "none.exe": "Keylogger, itp.",
    "key.exe": "Keylogger",
    "keysend.exe": "Keylogger",
    "keysender.exe": "Keylogger",
    "adware.exe": "Spyware",
    "end.exe": "Trojan",
    "logger.exe": "Keylogger",
    "rootstop.sys": "Rootkit",
    "rustock.sys": "Rootkit",
    "hackerdefender.sys": "Rootkit",
    "vanquish.sys": "Rootkit",
    "finspy.exe": "Spyware",
    "coolwebsearch.exe": "Spyware",
    "gator.exe": "Spyware",
    "cerber.exe": "Ransomware",
    "samsam.exe": "Ransomware",
    "Dharma.exe": "Ransomware",
    "spybot.exe": "Trojan",
    "netbus.exe": "Trojan",
    "subseven.exe": "Trojan",
    "zbot.dll": "Keylogger",
    "elitestealer.exe": "Keylogger",
    "keysweeper.js": "Keylogger",
    "necurs.sys": "Rootkit",
    "tdss.sys": "Rootkit",
    "ntrootkit.sys": "Rootkit",
    "superfish.exe": "Spyware",
    "browsersearch.exe": "Spyware",
    "finfisher.exe": "Spyware",
    "zango.exe": "Spyware",
    "teslacrypt.exe": "Ransomware",
    "crysis.exe": "Ransomware",
    "spora.exe": "Ransomware",
    "emolet.exe": "Trojan",
    "vawtrak.exe": "Trojan",
    "zeusgameover.exe": "Trojan",
    "hawkeye.exe": "Keylogger",
    "havkeye.exe": "Keylogger",
    "havkey.exe": "Keylogger",
    "havekeye.exe": "Keylogger",
    "havekey.exe": "Keylogger",
    "adwind.jar": "Keylogger",
    "predatorpain.exe": "Keylogger",
    "predator.exe": "Keylogger",
    "albinosun.sys": "Rootkit",
    "cerberp.sys": "Rootkit",
    "hackerguard.sys": "Rootkit",
    "hackerguardian.sys": "Rootkit",
    "xtremerat.exe": "Keylogger.rat",
    "zeus.exe": "Spyware",
        # extension dll
            "WindowsHandler.dll": "Stealer Trojan",
            "rndll86.dll": "Inne wirusy: Keylogger, Rat, itp.",
            "encryptor.dll": "Ransomware",
            "decryptor.dll": "Ransomware",
            "system32.dll": "Spyware",
            "taskmanager.dll": "Spyware",
            "driver.dll": "Rootkit",
            "ntoskrnl.dll": "Rootkit",
            "systemupdate.dll": "Keylogger",
            "keyboarddriver.dll": "Keylogger",
            "explorer.dll": "Trojan",
            "svchost.dll": "Trojan",
            "cryptolocker.dll": "Ransomware",
            "locky.dll": "Ransomware",
            "cryptominer.dll": "Cryptovalutes Miner",
            "miner.dll": "Cryptovalutes Miner",
            "bitcoin.dll": "Cryptovalutes Miner",
            "zeustrojan.dll": "Trojan",
            "Spyeye.dll": "Trojan",
            "backdoor.bladabindi.dll": "Trojan",
            "keylogger.dll": "Keylogger",
            "darkcometrat.dll": "Keylogger.rat",
            "poisonlvy.dll": "Keylogger",
            "alureon.dll": "Rootkit",
            "zeroaccess.dll": "Rootkit",
            "tdl-4.dll": "Rootkit",
            "adware.eorezo.dll": "Spyware",
            "winspy.dll": "Spyware",
            "finfisher.dll": "Spyware",
            "gandcrab.dll": "Ransomware",
            "ryuk.dll": "Ransomware",
            "maze.dll": "Ransomware",
            "darkcomet.dll": "Ransomware",
            "xxx.dll": "Ransomware",
            "keybase.dll": "Keylogger",
            "blackshades.dll": "Keylogger",
            "elitekeylogger.dll": "Keylogger",
            "none.dll": "Keylogger, itp.",
            "key.dll": "Keylogger",
            "keysend.dll": "Keylogger",
            "keysender.dll": "Keylogger",
            "adware.dll": "Spyware",
            "end.dll": "Trojan",
            "logger.dll": "Keylogger",
            "rootstop.dll": "Rootkit",
            "rustock.dll": "Rootkit",
            "hackerdefender.dll": "Rootkit",
            "vanquish.dll": "Rootkit",
            "finspy.dll": "Spyware",
            "coolwebsearch.dll": "Spyware",
            "gator.dll": "Spyware",
            "cerber.dll": "Ransomware",
            "samsam.dll": "Ransomware",
            "Dharma.dll": "Ransomware",
            "spybot.dll": "Trojan",
            "netbus.dll": "Trojan",
            "subseven.dll": "Trojan",
            "zbot.dll": "Keylogger",
            "elitestealer.dll": "Keylogger",
            "keysweeper.dll": "Keylogger",
            "necurs.dll": "Rootkit",
            "tdss.dll": "Rootkit",
            "ntrootkit.dll": "Rootkit",
            "superfish.dll": "Spyware",
            "browsersearch.dll": "Spyware",
            "finfisher.dll": "Spyware",
            "zango.dll": "Spyware"
    
        
        # Add Known Viruses name "name(virus.exe)": "name_virus(Trojan.keylogger)"
    }
    for root, dirs, files in os.walk(path):
        for file in files:
            file_path = os.path.join(root, file)
            for threat_file in threats.keys():
                if threat_file.lower() == file.lower():
                    threat_name = threats[threat_file]
                    print("Found Virus:", threat_name)
                    print("Localization:", file_path)
                    print("Antyvirus fast scan by @azael1337 <--- Found in Discord ;)")

def main():
    scan_directories = [
    #add Known File Path
        os.path.expandvars("%appdata%"),
        os.path.expandvars("%temp%"),
        os.path.expandvars("temp"),
        
    ]
    
    for directory in scan_directories:
        scan_directory(directory)

if __name__ == "__main__":
    main()
